version: "3.7"
services:
    haproxy:
      image: haproxy:2.0.5-alpine
      volumes:
        - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      expose:
      - "8404"
      - "9009"
    consul:
      image: consul
      expose:
      - "8500"
    cortex1:
      image: cortexproject/cortex:master-0976147
      command: -config.file=/etc/single-process-config.yaml -ring.store=consul  -consul.hostname=consul:8500
      expose:
      - "9009"
      volumes:
        - "./config/single-process-config.yaml:/etc/single-process-config.yaml"
    cortex2:
      image: cortexproject/cortex:master-0976147
      command: -config.file=/etc/single-process-config.yaml -ring.store=consul  -consul.hostname=consul:8500
      expose:
      - "9009"
      volumes:
        - "./config/single-process-config.yaml:/etc/single-process-config.yaml"
    cortex3:
      image: cortexproject/cortex:master-0976147
      command: -config.file=/etc/single-process-config.yaml -ring.store=consul  -consul.hostname=consul:8500
      expose:
      - "9009"
      volumes:
        - "./config/single-process-config.yaml:/etc/single-process-config.yaml"
    grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      volumes:
        - "./config/grafana.ini:/etc/grafana/grafana.ini"
    oauth2-proxy:
      image:  quay.io/oauth2-proxy/oauth2-proxy
      environment:
        - test=asds
      command:
        - /bin/oauth2-proxy
        - --config=/etc/oauth2-proxy.cfg
        - --provider-display-name="My OIDC Provider"
        - --cookie-secure=false
        - --set-xauthrequest=true
        - --email-domain=*
        - --cookie-secret=ZZZZZZZZZZZZZZZZ
        - --oidc-issuer-url=https://iam.cloud.infn.it/
        - --client-id=__CLIENT_ID__
        - --client-secret=__CLIENT_ID__
        - --pass-user-headers=true
      ports:
        - 4180:4180
      volumes:
        - "./config/oauth2-proxy.cfg:/etc/oauth2-proxy.cfg"
    node-exporter:
      image: basi/node-exporter
      expose:
      - "9100"
    prometheus:
      image: prom/prometheus
      expose:
      - "9090"
      volumes:
        - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    cortex-tenant:
      image: dciangot/cortex-tenant
      command:
        - cortex-tenant
        - -config
        - /etc/cortex-tenant.yml
      environment:
        - test=asds
      expose:
      - "8080"
      volumes:
        - "./config/cortex-tenant.yml:/etc/cortex-tenant.yml"

